/* eslint-disable @next/next/no-html-link-for-pages */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>D3G3N | Community Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img className='header-logo' src='/imgs/logo.png' alt="logo"/>

        <p className={styles.description}> 
          Here are a few resrouces <br/> to get started
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
          <a href="/CoverJam" className={styles.card}>
            <h2>CoverJam Oct 2022 &rarr;</h2>
            <img class="thumbnail" src='/imgs/MetaCoverJam_CoverArtPhoto.png' alt="CoverJam"/>
            <br/><br/>
            <p> Calling all creatives from 2D, 3D & hand draw artist </p>
          </a>

          <a href="https://discord.gg/v6ZuXfmyvy" target="blank" className={styles.card}>
          <h2>Community Server &rarr;</h2>
            <img class="thumbnail" src='/imgs/Meta_Discord.png' alt="CoverJam"/>
            <br/><br/>
            <p> Join the conversation with creatives and dev team!  </p>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>Best Frens &#128274;</h2>
            <img class="thumbnail" src='/imgs/Meta_Partner.png' alt="CoverJam"/>
            <br/><br/>
            <p>Our Partners for the blockchain experience </p>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>Fren Portals &#128274;</h2>
            <img class="thumbnail" src='/imgs/Meta_Portal.png' alt="CoverJam"/>
            <br/><br/>
            <p>Find out what our community is up to! </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
     
      </footer>
    </div>
  )
}
